export const ADD_INGRIDIENT = 'ADD_INGRIDIENT';
export const REMOVE_INGRIDIENT = 'REMOVE_INGRIDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCHED_INGREDIENTS_FAILED = 'FETCHED_INGREDIENTS_FAILED';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCES = 'PURCHASE_BURGER_SUCCES';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCHED_ORDERS_START = 'FETCHED_ORDERS_START';
export const FETCHED_ORDERS_SUCCES = 'FETCHED_ORDERS_SUCCES';
export const FETCHED_ORDERS_FAIL = 'FETCHED_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';